db: /tmp/db0
port: 9090
syncSessionLimit: 2
syncSessionPeriod: 10000
syncPushBroadcastLimit: 0
gcInterval: 300000
gcPurgeAge: 600000
merkleDepth: 19
logLevel: debug
alerts:
    forwardInterval: 1000
history:
    forwardInterval: 1000
peers:
    - id: WWRL000001
      host: 127.0.0.1
      port: 9191
tls:
    clientCertificate: ../test_certs/WWRL000000.client.cert.pem
    clientKey: ../test_certs/WWRL000000.client.key.pem
    serverCertificate: ../test_certs/WWRL000000.server.cert.pem
    serverKey: ../test_certs/WWRL000000.server.key.pem
    rootCA: ../test_certs/ca-chain.cert.pem