#db: /tmp/db0
db: /home/jrife/Desktop/new-db
port: 9090
syncSessionLimit: 2
merkleDepth: 19
peers:
    - id: WWRL000001
      host: 127.0.0.1
      port: 9191
tls:
    clientCertificate: ../test_certs/WWRL000000.client.cert.pem
    clientKey: ../test_certs/WWRL000000.client.key.pem
    serverCertificate: ../test_certs/WWRL000000.server.cert.pem
    serverKey: ../test_certs/WWRL000000.server.key.pem
    rootCA: ../test_certs/ca-chain.cert.pem